name: Automação de relatório/dashboard
on:
    push:
        branches: ['main']
    schedule:
        - cron: '0 0 * * *'

jobs:
    Automacao:
        runs-on: ubuntu-24.04
        steps:
            - name: Clonar repositório
              uses: actions/checkout@v4
            
            - name: Instalar Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.12.3'  # Altere para 3.11 se necessário

            - name: Instalar Poetry
              uses: snok/install-poetry@v1
              with:
                version: 1.8.5
            
            - name: Instalar Quarto
              uses: quarto-dev/quarto-actions/setup@v2
              with:
                version: 1.6.37

            - name: Verificar Quarto
              run: quarto --version

            - name: Instalar Jupyter e PyYAML
              run: |
                poetry add pyyaml jupyter

            - name: Atualização de relatório
              run: |
                poetry config virtualenvs.prefer-active-python true
                poetry run quarto render Programacao_Python_2/relatorio/relatorio.qmd

            - name: Executar ETL
              run:
                poetry run python dashboard/etl.py

            - name: Adicionar conta rsconnect
              run:
                 poetry run rsconnect add --account ${{ secrets.ACCOUNT }} --name ${{ secrets.NAME }} --token ${{ secrets.TOKEN }} --secret ${{ secrets.SECRET }} 

            - name: Deploy da dashboard
              run:
                 poetry run rsconnect deploy shiny dashboard --name economistscnpi --title 'Macro Copa'     

            - name: Commit & Push
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                commit_message: Atualização de relatorio de dashboard  
